services:
  kvs-main:
    environment:
      - RUST_LOG=info
    build:
      context: .
      dockerfile: Dockerfile
      target: kvs-main
    ports:
      - "3030:3030"
    volumes:
      - ./sample_configuration/config.json:/config.json
    networks:
      - kvs-network

  kvs-replica:
    environment:
      - RUST_LOG=info
    build:
      context: .
      dockerfile: Dockerfile
      target: kvs-replica
    ports:
      - "3031:3030"
    volumes:
      - ./sample_configuration/config_replica.json:/config.json
    networks:
      - kvs-network
    depends_on:
      - kvs-main

networks:
  kvs-network:
    driver: bridge
